server:
  port: 8080

# Variables defined for the project
forum:
  # Role for accounts
  #  role:
  #    user: USER
  #    admin: ADMIN
  # Postgres Connection
  db-conn:
    host: 127.0.0.1
    port: 5432
    database: your-database
    username: your-username
    password: your-password
  # Jwt String
  jwt:
    secret: s71uE1N861fVWFi8pjZqHwG15NLOB5vCGq0-Cb4w10tTtY7-WPwXyM_cQaSCdMid
    access-token-expiration: 36000000 # 10 hours
    refresh-token-expiration: 864000000 # 10 days

  # Id for Snowflake
  snowflake:
    worker-id: 10
    datacenter-id: 15

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${forum.db-conn.username}
    password: ${forum.db-conn.password}
    url: jdbc:postgresql://${forum.db-conn.host}:${forum.db-conn.port}/${forum.db-conn.database}
  #    hikari:
  #      max-lifetime: 60000 # 10 minutes
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      username: ${forum.db-conn.username}
      password: ${forum.db-conn.password}
      encoding: UTF-8
      mode: always
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: update
    open-in-view: false


  jackson:
    # 日期序列化格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 序列化和反序列化属性配置，默认是保留字段名称，并从方法中删除 set/get/is 前缀（以及小写首字母大写字符序列）
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy

    # 序列化配置，有多个
    serialization:
      # 底层格式化序列后的JSON，换行、缩进等
      indent-output: true
      # 忽略无法转换的对象
      fail_on_empty_beans: true
    # 反序列化配置，有多个
    deserialization:
      # 解析json时，遇到不存在的属性就忽略
      fail_on_unknown_properties: false
    # 配置@JsonInclude默认包含哪些属性
    defaultPropertyInclusion: use_defaults
    parser:
      # 允许特殊和转义符
      allow_unquoted_control_chars: true
      # 允许单引号
      allow_single_quotes: true
    # 配置时区
    timeZone: Asia/Shanghai
    # 配置地区
    locale: zh_CN
